#%RAML 1.0 NamedExample
value:
  -
   CustID: C1001
   CustName: Charlie Chaplin
   CustPhone: 8080750356
   CustCity: New York
   CustPostalCode: 245876
   CustMail: charlie.chaplin@gmail.com
  -
   CustID: C1002
   CustName: Alan Harper
   CustPhone: 9080247565
   CustCity: Belarus
   CustPostalCode: 546981
   CustMail: alan.harper@qcs.com